consul:
    image: qnib/alpn-consul
    hostname: consul
    container_name: consul
    ports:
     - 8500
    environment:
     - DC_NAME=dc1
     - CONSUL_BOOTSTRAP_EXPECT=1
    dns: 127.0.0.1

elasticsearch:
    image: qnib/alpn-elasticsearch
    dns: 127.0.0.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
     - "9200:9200"
    environment:
     - DC_NAME=dc1
     - FORWARD_TO_ELASTICSEARCH=true
     - COLLECT_METRICS=false
     - SKIP_PSWATCH=true
    links:
     - consul:consul
    privileged: true

kopf:
    image: qnib/kopf
    hostname: kopf
    container_name: kopf
    environment:
     - DC_NAME=dc1
    dns: 127.0.0.1
    ports:
     - 8088:80
    links:
     - consul:consul

kibana4:
  hostname: kibana4
  container_name: kibana4
  image: qnib/kibana4
  ports:
   - "5601:5601"
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=false
  - CNT_TYPE=service
  - SKIP_PSWATCH=true
  - COLLECT_METRICS=false
  - HTTPPORT=9200
  dns: 127.0.0.1
  privileged: true
  links:
  - consul:consul
